version: '3'
services:
  DataScienceKit:
    image: mkwp/ds:adv-kit0.1
    # build: .
    ports:
      - "8880:8880"
    volumes:
      - .:/mnt/code
      # - C:\:/mnt/s883
    command: /bin/bash /usr/entrypoint.sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
