version: '3'
services:
  DataScienceKit:
    image: mkwp/ds:adv-kit0.1
    build: .
    ports:
      - "8880:8880"
    volumes:
      - .:/mnt/workspace
      # - nas-share:/mnt/workspace
    command: /bin/bash /usr/entrypoint.sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t

# volumes:
#   nas-share:
#     driver_opts:
#       type: cifs
#       o: "username=[username],password=[password]"
#       device: "//my-nas/share"
